version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://raj:Rajshah11@db:5432/liquicity
      - POSTGRES_HOST=db
      - POSTGRES_USER=raj
      - POSTGRES_PASSWORD=Rajshah11
      - POSTGRES_DB=liquicity
    depends_on:
      - db
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:8000
    depends_on:
      - api
    restart: always
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=raj
      - POSTGRES_PASSWORD=Rajshah11
      - POSTGRES_DB=liquicity
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: 