"""create onramp tables

Revision ID: 20240723_onramp_tables
Revises: 
Create Date: 2025-07-23
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20240723_onramp_tables"
down_revision = None  # set to latest revision id when integrating
branch_labels = None
depends_on = None


order_status_enum = postgresql.ENUM(
    "pending",
    "processing",
    "completed",
    "failed",
    name="onramp_order_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    order_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "onramp_payment_methods",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("payment_method_id", sa.String(), nullable=False, unique=True),
        sa.Column("plaid_token_hash", sa.String(), nullable=False),
        sa.Column("fiat_rail", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=True),
    )

    op.create_table(
        "onramp_orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("payment_method_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("velafi_order_id", sa.String(), nullable=False, unique=True),
        sa.Column("fiat_amount", sa.Numeric(), nullable=False),
        sa.Column("fiat_currency", sa.String(length=3), nullable=False),
        sa.Column("fiat_rail", sa.String(), nullable=False),
        sa.Column("status", order_status_enum, nullable=False, server_default="pending"),
        sa.Column("usdc_amount", sa.Numeric(), nullable=True),
        sa.Column("quote_rate", sa.Numeric(), nullable=True),
        sa.Column("fee_usd", sa.Numeric(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )

    # Indexes
    op.create_index("idx_onramp_orders_user", "onramp_orders", ["user_id"])
    op.create_index("idx_onramp_orders_status", "onramp_orders", ["status"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_onramp_orders_status", table_name="onramp_orders")
    op.drop_index("idx_onramp_orders_user", table_name="onramp_orders")
    op.drop_table("onramp_orders")
    op.drop_table("onramp_payment_methods")
    order_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ### 