name: Codespaces Prebuilds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup prebuild
        uses: github/codespaces-precreate@v1
        with:
          devcontainer-path: '.devcontainer/devcontainer.json' 